In [2]:
import numpy as np

In [9]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
random_matrix = np.random.randint(1, 11, (5, 5))
print(random_matrix)

[[ 6  6 10  3  1]
 [ 9 10  2  9  2]
 [ 7  7  9  5  5]
 [ 8 10  7  6  2]
 [ 9 10  3  8  1]]


In [12]:
random_float_matrix = np.random.rand(4, 4)
print(random_float_matrix)

[[0.92171554 0.7662882  0.27648983 0.23545464]
 [0.72635598 0.39919159 0.47727227 0.13739226]
 [0.52479054 0.6297159  0.66497379 0.99348043]
 [0.22217347 0.25362517 0.95047368 0.96994896]]


In [57]:
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Addition: [14 13 15 13 10]
Subtraction: [ 4 -3 -3 -7  8]
Multiplication: [45 40 54 30  9]


In [54]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([7, 6, 5, 4, 3, 2, 1])
dot_product = np.dot(vector1, vector2)
print("Dot product:", dot_product)

Dot product: 84


In [55]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))
matrix_product = np.dot(matrix1, matrix2)
print("Matrix product:")
print(matrix_product)

Matrix product:
[[128 118 120]
 [ 58  53  50]]


In [56]:
matrix3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix3)
print("Inverse matrix:")
print(inverse_matrix)

Inverse matrix:
[[ 0.0026178  -0.09685864  0.10732984]
 [-0.19109948  0.07068063  0.16492147]
 [ 0.21465969  0.05759162 -0.19895288]]


In [51]:
matrix4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix4)
print("Transposed matrix:")
print(transposed_matrix)

Transposed matrix:
[[0.89920292 0.52690034 0.52147433 0.40187339]
 [0.84283309 0.44209022 0.11111361 0.59741717]
 [0.65696057 0.69004006 0.68737403 0.88061163]
 [0.67128211 0.90591819 0.77888865 0.86356931]]


In [50]:
matrix5 = np.random.randint(1, 11, (3, 4))
vector3 = np.random.randint(1, 11, 4)
matrix_vector_product = np.dot(matrix5, vector3)
print("Matrix-vector product:")
print(matrix_vector_product)

Matrix-vector product:
[138 250 182]


In [49]:
matrix6 = np.random.rand(2, 3)
vector4 = np.random.rand(3)
matrix_vector_product2 = np.dot(matrix6, vector4)
print("Matrix-vector product 2:")
print(matrix_vector_product2)

Matrix-vector product 2:
[0.2369928  1.19799691]


In [48]:
matrix7 = np.random.randint(1, 11, (2, 2))
matrix8 = np.random.randint(1, 11, (2, 2))
elementwise_multiplication = matrix7 * matrix8
print("Elementwise multiplication:")
print(elementwise_multiplication)

Elementwise multiplication:
[[ 7 16]
 [18 63]]


In [47]:
matrix9 = np.random.randint(1, 11, (2, 2))
matrix10 = np.random.randint(1, 11, (2, 2))
matrix_product2 = np.dot(matrix9, matrix10)
print("Matrix product 2:")
print(matrix_product2)

Matrix product 2:
[[91 55]
 [36 75]]


In [46]:
matrix11 = np.random.randint(1, 101, (5, 5))
matrix_sum = np.sum(matrix11)
print("Matrix sum:", matrix_sum)

Matrix sum: 1308


In [45]:
matrix12 = np.random.randint(1, 11, (4, 4))
matrix13 = np.random.randint(1, 11, (4, 4))
matrix_difference = matrix12 - matrix13
print("Matrix difference:")
print(matrix_difference)

Matrix difference:
[[ 5  3  7 -1]
 [-4 -1 -3 -2]
 [-5  2 -1  2]
 [-2 -4  6  7]]


In [44]:
matrix14 = np.random.rand(3, 3)
row_sums = np.sum(matrix14, axis=1)
column_vector = np.reshape(row_sums, (3, 1))
print("Column vector:")
print(column_vector)

Column vector:
[[1.75252846]
 [1.02093905]
 [2.2419759 ]]


In [43]:
matrix15 = np.random.randint(-10, 10, (3, 4))
squared_matrix = np.square(matrix15)
print("Squared matrix:")
print(squared_matrix)

Squared matrix:
[[  1  49   4 100]
 [  1  36   1  36]
 [  9   9  36  25]]


In [42]:
vector5 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector5)
print("Square root vector:")
print(sqrt_vector)

Square root vector:
[4.47213595 1.         5.38516481 3.74165739]
